import type { ScenarioSolution } from "./types";

export const DEMO_SCENARIO_SOLUTIONS: ScenarioSolution[] = [
  {
    id: "DEMO-SOLUTION-MOUNTAIN-POWER", name: "样例·山区电力巡检组合方案", category: "巡检场景方案", scenario: "山区电力巡检",
    summary: "以重载抗风平台承担复杂地形主任务，并以长续航平台补充常规杆塔巡检。",
    productIds: ["DEMO-T60", "DEMO-X8"], priceYuan: 366000, enduranceMinutes: 55, windResistanceMps: 14, payloadKg: 4,
    tags: ["山区巡检", "电力巡检", "抗风", "长续航", "重载", "专业作业"],
    suitableConditions: ["山区或复杂地形", "需要抗风与载荷冗余", "具备专业飞手和作业组织能力"],
    limitations: ["样例价格不含真实载荷、服务和实施费用", "正式选型需核对空域、链路和作业规范"],
    source: "Mock场景方案库 v1.0 / DEMO-SOLUTION-MOUNTAIN-POWER", updatedAt: "2026-07-26",
  },
  {
    id: "DEMO-SOLUTION-PARK", name: "样例·园区日常巡检组合方案", category: "巡检场景方案", scenario: "园区巡检",
    summary: "以长续航巡检平台覆盖日常航线，并配置轻型平台承担快速复查。",
    productIds: ["DEMO-X8", "DEMO-S3"], priceYuan: 266000, enduranceMinutes: 55, windResistanceMps: 12, payloadKg: 2.5,
    tags: ["园区巡检", "长续航", "快速交付", "常态化作业"],
    suitableConditions: ["固定园区航线", "强调交付周期和日常可用性", "中等载荷需求"],
    limitations: ["不适用于高载荷投送", "正式方案需结合航线、机库和业务系统联动"],
    source: "Mock场景方案库 v1.0 / DEMO-SOLUTION-PARK", updatedAt: "2026-07-26",
  },
  {
    id: "DEMO-SOLUTION-EMERGENCY", name: "样例·山区应急保障组合方案", category: "应急场景方案", scenario: "山区应急保障",
    summary: "以大载荷保障平台承担投送，并以高抗风巡检平台执行现场侦察。",
    productIds: ["DEMO-R6", "DEMO-T60"], priceYuan: 423000, enduranceMinutes: 45, windResistanceMps: 15, payloadKg: 5,
    tags: ["山区巡检", "应急保障", "物资投送", "抗风", "重载", "专业作业"],
    suitableConditions: ["山区应急响应", "需要物资投送", "具备专业保障团队"],
    limitations: ["样例未包含通信、指挥和现场保障系统", "高风险任务必须由专业人员复核"],
    source: "Mock场景方案库 v1.0 / DEMO-SOLUTION-EMERGENCY", updatedAt: "2026-07-26",
  },
];

export const AG003_CAPABILITY_COVERAGE = [
  ["110-A-002", "商城场景方案类目匹配", "mock-demonstrated"],
  ["110-A-003", "已上架场景方案候选推荐", "mock-demonstrated"],
  ["110-A-004", "商城场景方案推荐依据生成", "mock-demonstrated"],
  ["110-A-005", "商城场景方案适用条件判断", "mock-demonstrated"],
  ["110-A-006", "商城场景方案差距事项生成", "mock-demonstrated"],
  ["110-A-001", "商城场景方案需求识别", "mock-demonstrated"],
  ["214-A-005", "商品搜索候选匹配", "mock-demonstrated"],
  ["214-A-001", "商品搜索意图理解", "mock-demonstrated"],
  ["214-A-002", "商品型号识别", "mock-demonstrated"],
  ["214-A-003", "商品搜索词纠错", "mock-demonstrated"],
  ["214-A-004", "商品类目推断", "mock-demonstrated"],
  ["214-A-006", "商品搜索相关性评分", "mock-demonstrated"],
  ["089-A-009", "反馈条件再匹配", "adapter-ready"],
  ["089-A-009", "图片匹配效果判断", "adapter-ready"],
  ["089-A-009", "图片匹配调整方向识别", "adapter-ready"],
  ["089-A-005", "图片相似商品匹配", "adapter-ready"],
  ["089-A-006", "相似候选商品业务适配判断", "adapter-ready"],
  ["089-A-007", "相似程度排序", "adapter-ready"],
  ["089-A-008", "差异特征说明", "adapter-ready"],
  ["089-A-008", "相似特征说明", "adapter-ready"],
  ["089-A-003", "图片主体识别", "adapter-ready"],
  ["089-A-004", "产品特征提取", "adapter-ready"],
  ["089-A-002", "图片有效性检查", "adapter-ready"],
  ["232-A-008", "C2C候选商品评分", "adapter-ready"],
  ["232-A-009", "C2C初始推荐", "adapter-ready"],
  ["232-A-019", "C2C推荐依据生成", "adapter-ready"],
  ["232-A-004", "整机类商品匹配", "adapter-ready"],
  ["232-A-005", "零件类商品匹配", "adapter-ready"],
  ["232-A-007", "C2C候选商品可推荐性判断", "adapter-ready"],
  ["232-A-018", "同城交易可达性综合判断", "adapter-ready"],
  ["232-A-010", "C2C推荐反馈识别", "adapter-ready"],
  ["232-A-010", "C2C推荐效果评价", "adapter-ready"],
] as const;
