export const AG002_CONFIG = {
  workflowVersion: "1.1.0",
  ruleVersion: "AG-002 说明书解读规则 v1.1",
  defaultManualId: "DEMO-MANUAL-X8",
  maxSections: 5,
  maxSteps: 8,
  reliability: {
    aiPlatform: { timeoutMs: 3_000, maxAttempts: 2, circuitFailureThreshold: 3, circuitResetMs: 30_000 },
    documentData: { timeoutMs: 3_000, maxAttempts: 2, circuitFailureThreshold: 3, circuitResetMs: 30_000 },
  },
  capabilityCoverage: [
    { requirement_id: "121-A-002", capability: "安全事项要点提取", status: "mock-demonstrated" },
    { requirement_id: "085-A-015", capability: "安全风险提示生成", status: "mock-demonstrated" },
    { requirement_id: "085-A-015", capability: "禁止操作提示生成", status: "mock-demonstrated" },
    { requirement_id: "085-A-015", capability: "合规要求场景提示生成", status: "mock-demonstrated" },
    { requirement_id: "085-A-012", capability: "说明书操作步骤通俗解读", status: "mock-demonstrated" },
    { requirement_id: "085-A-012", capability: "专业术语转换", status: "mock-demonstrated" },
    { requirement_id: "085-A-013", capability: "说明书场景语义检索", status: "adapter-ready" },
    { requirement_id: "085-A-014", capability: "场景化操作指引生成", status: "mock-demonstrated" },
    { requirement_id: "121-A-002", capability: "操作步骤摘要", status: "mock-demonstrated" },
    { requirement_id: "121-A-002", capability: "故障排查路径摘要", status: "mock-demonstrated" },
    { requirement_id: "121-A-002", capability: "产品核心能力与适用边界摘要", status: "mock-demonstrated" },
    { requirement_id: "085-A-016", capability: "说明书图示含义解读", status: "adapter-ready" },
    { requirement_id: "085-A-016", capability: "说明书章节与图表关系理解", status: "adapter-ready" },
  ],
} as const;
