import type { DemoPolicyDocument } from "./types";

export const DEMO_POLICY_DOCUMENTS: DemoPolicyDocument[] = [
  {
    id: "DEMO-POLICY-FLIGHT-2025",
    title: "样例·低空飞行活动管理办法（试行版）",
    documentNumber: "样政〔2025〕01号",
    issuer: "样例低空事务协调机构（虚构）",
    documentType: "policy",
    jurisdiction: "样例示范区",
    version: "2025试行版",
    publishedAt: "2025-06-15",
    effectiveFrom: "2025-07-01",
    effectiveTo: "2026-07-31",
    versionChainId: "DEMO-CHAIN-FLIGHT-MGMT",
    replacesId: null,
    aliases: ["飞行活动管理办法", "试行版", "旧政策", "2025版"],
    sourceType: "虚构样例政策材料",
    versionChanges: [],
    sections: [
      {
        id: "flight-2025-scope", heading: "第四条 适用范围", locator: "第四条",
        text: "本办法适用于样例示范区内使用民用无人驾驶航空器开展商业巡检、测绘和影像采集的运营主体。个人娱乐活动按照其他规定管理。",
        plainLanguage: "试行版主要覆盖样例示范区内的商业巡检、测绘和影像采集，个人娱乐活动不在本条范围内。",
        topics: ["scope", "applicability"], keywords: ["适用范围", "商业巡检", "测绘", "影像采集", "运营主体"],
        appliesTo: ["运营企业", "飞行服务商", "巡检企业"], scenarios: ["园区巡检", "电力巡检", "测绘", "商业航拍"],
      },
      {
        id: "flight-2025-filing", heading: "第八条 活动报备", locator: "第八条",
        text: "运营主体应在计划飞行前两个工作日提交活动报备，说明运营主体、航空器、航线、时间窗口和现场联系人。",
        plainLanguage: "试行版要求在计划飞行前两个工作日报备主体、设备、航线、时间和联系人。",
        topics: ["filing", "operation"], keywords: ["报备", "两个工作日", "航线", "时间窗口", "联系人"],
        appliesTo: ["运营企业", "飞行服务商", "巡检企业"], scenarios: ["园区巡检", "电力巡检", "测绘", "商业航拍"],
      },
      {
        id: "flight-2025-records", heading: "第十二条 运行记录", locator: "第十二条",
        text: "运营主体应留存飞行日期、航空器、操作者、航线和异常情况等运行记录，保存期限不少于六个月。",
        plainLanguage: "试行版要求保存基本运行记录至少六个月。",
        topics: ["record_retention", "operation"], keywords: ["运行记录", "六个月", "异常情况", "保存期限"],
        appliesTo: ["运营企业", "飞行服务商", "巡检企业"], scenarios: ["园区巡检", "电力巡检", "测绘", "商业航拍"],
      },
    ],
  },
  {
    id: "DEMO-POLICY-FLIGHT-2026",
    title: "样例·低空飞行活动管理办法（2026修订稿）",
    documentNumber: "样政〔2026〕08号",
    issuer: "样例低空事务协调机构（虚构）",
    documentType: "policy",
    jurisdiction: "样例示范区",
    version: "2026修订稿",
    publishedAt: "2026-07-15",
    effectiveFrom: "2026-08-01",
    effectiveTo: null,
    versionChainId: "DEMO-CHAIN-FLIGHT-MGMT",
    replacesId: "DEMO-POLICY-FLIGHT-2025",
    aliases: ["飞行活动管理办法", "修订稿", "新政策", "2026版"],
    sourceType: "虚构样例政策材料",
    sections: [
      {
        id: "flight-2026-scope", heading: "第四条 适用范围", locator: "第四条",
        text: "本办法适用于样例示范区内使用民用无人驾驶航空器开展商业巡检、测绘、影像采集和低空物流配送的运营主体。",
        plainLanguage: "修订稿在原有巡检、测绘和影像采集基础上，将低空物流配送纳入适用范围。",
        topics: ["scope", "applicability", "logistics"], keywords: ["适用范围", "商业巡检", "低空物流", "运营主体"],
        appliesTo: ["运营企业", "飞行服务商", "巡检企业", "物流企业"], scenarios: ["园区巡检", "电力巡检", "测绘", "商业航拍", "物流配送"],
      },
      {
        id: "flight-2026-filing", heading: "第九条 分级报备", locator: "第九条",
        text: "运营主体应在计划飞行前三个工作日提交分级活动报备，补充风险等级、电子围栏范围、现场责任人和应急联系方式。",
        plainLanguage: "修订稿将报备提前到三个工作日，并增加风险等级、电子围栏和现场责任人等信息。",
        topics: ["filing", "operation", "business_impact"], keywords: ["分级报备", "三个工作日", "风险等级", "电子围栏", "现场责任人"],
        appliesTo: ["运营企业", "飞行服务商", "巡检企业", "物流企业"], scenarios: ["园区巡检", "电力巡检", "测绘", "商业航拍", "物流配送"],
      },
      {
        id: "flight-2026-change", heading: "第十三条 重大变更", locator: "第十三条",
        text: "航空器、主要航线、时间窗口或现场责任人发生重大变化的，运营主体应重新提交活动报备。",
        plainLanguage: "修订稿新增重大变更重新报备要求，设备、主要航线、时间或责任人变化时不能沿用原报备。",
        topics: ["filing", "operation", "business_impact"], keywords: ["重大变更", "重新报备", "航空器", "主要航线", "责任人"],
        appliesTo: ["运营企业", "飞行服务商", "巡检企业", "物流企业"], scenarios: ["园区巡检", "电力巡检", "测绘", "商业航拍", "物流配送"],
      },
      {
        id: "flight-2026-records", heading: "第十六条 数字化记录", locator: "第十六条",
        text: "运营主体应保存数字化运行记录不少于十二个月；涉及异常事件的记录保存期限不少于二十四个月。",
        plainLanguage: "修订稿把一般记录期限延长到十二个月，异常事件记录延长到二十四个月。",
        topics: ["record_retention", "operation", "business_impact"], keywords: ["数字化记录", "十二个月", "二十四个月", "异常事件"],
        appliesTo: ["运营企业", "飞行服务商", "巡检企业", "物流企业"], scenarios: ["园区巡检", "电力巡检", "测绘", "商业航拍", "物流配送"],
      },
      {
        id: "flight-2026-effective", heading: "第十八条 生效与替代", locator: "第十八条",
        text: "本办法自2026年8月1日起施行，同时替代样政〔2025〕01号试行版。",
        plainLanguage: "2026修订稿将在2026年8月1日生效，届时替代2025试行版。",
        topics: ["version_status", "timeliness"], keywords: ["生效", "替代", "2026年8月1日", "试行版"],
        appliesTo: [], scenarios: [],
      },
    ],
    versionChanges: [
      { id: "change-scope-logistics", topic: "适用范围", changeType: "modified", oldSectionId: "flight-2025-scope", newSectionId: "flight-2026-scope", explanation: "适用场景由巡检、测绘和影像采集扩展到低空物流配送。", businessImpact: "物流企业需要把飞行活动纳入修订稿要求的报备和运行管理准备。" },
      { id: "change-filing", topic: "活动报备", changeType: "modified", oldSectionId: "flight-2025-filing", newSectionId: "flight-2026-filing", explanation: "报备提前期由两个工作日调整为三个工作日，并新增风险等级、电子围栏和现场责任人字段。", businessImpact: "运营团队需要提前准备更完整的风险和责任信息，现有报备表单可能需要调整。" },
      { id: "change-resubmit", topic: "重大变更", changeType: "added", oldSectionId: "flight-2025-filing", newSectionId: "flight-2026-change", explanation: "新增设备、主要航线、时间窗口或现场责任人重大变化后的重新报备要求。", businessImpact: "任务变更管理需要增加重新报备判断，不能默认沿用原报备结果。" },
      { id: "change-retention", topic: "运行记录", changeType: "modified", oldSectionId: "flight-2025-records", newSectionId: "flight-2026-records", explanation: "一般记录保存期由六个月延长至十二个月，异常事件记录需保存二十四个月。", businessImpact: "企业需要检查数字化记录字段、存储周期和异常事件归档流程。" },
    ],
  },
  {
    id: "DEMO-STANDARD-LOGISTICS-2026",
    title: "样例·低空物流运行安全规范",
    documentNumber: "样标 T/DEMO 1001—2026",
    issuer: "样例低空标准化组织（虚构）",
    documentType: "standard",
    jurisdiction: "样例行业范围",
    version: "2026样例版",
    publishedAt: "2026-05-10",
    effectiveFrom: "2026-06-01",
    effectiveTo: null,
    versionChainId: "DEMO-CHAIN-LOGISTICS-STANDARD",
    replacesId: null,
    aliases: ["物流安全规范", "低空物流标准", "安全规范"],
    sourceType: "虚构样例行业标准",
    versionChanges: [],
    sections: [
      { id: "logistics-standard-risk", heading: "5.2 航线风险评估", locator: "第5.2条", text: "运行单位应在启用航线前识别人口密集区、障碍物、通信盲区和备降点，并形成可复核的风险评估记录。", plainLanguage: "物流航线启用前要评估人员、障碍物、通信和备降条件，并留下可复核记录。", topics: ["operation_safety", "logistics", "business_impact"], keywords: ["航线风险", "障碍物", "通信盲区", "备降点"], appliesTo: ["物流企业", "运营企业", "飞行服务商"], scenarios: ["物流配送"] },
      { id: "logistics-standard-threshold", heading: "6.3 运行条件核对", locator: "第6.3条", text: "每次任务前应核对航空器载荷、电池状态、天气阈值和目的地接收条件；任一关键条件不满足时不得执行任务。", plainLanguage: "每次配送前都要核对载荷、电池、天气和接收条件，关键项不满足就停止任务。", topics: ["operation_safety", "logistics", "applicability"], keywords: ["载荷", "电池", "天气阈值", "接收条件"], appliesTo: ["物流企业", "运营企业", "飞行服务商"], scenarios: ["物流配送"] },
      { id: "logistics-standard-drill", heading: "7.4 应急演练", locator: "第7.4条", text: "运行单位应至少每六个月组织一次链路中断、目的地不可用或异常降落场景的应急演练，并记录改进项。", plainLanguage: "物流运行单位至少每六个月演练一次典型异常场景，并记录需要改进的事项。", topics: ["operation_safety", "logistics", "business_impact"], keywords: ["应急演练", "六个月", "链路中断", "异常降落"], appliesTo: ["物流企业", "运营企业", "飞行服务商"], scenarios: ["物流配送", "应急处置"] },
    ],
  },
];
